Style/VerboseBlock:
  Description: Identifies usage of collapsible single expression blocks.
  ExcludeCallsWithBlock: true
  ExcludeMultipleLineBlocks: false
  ExcludePrefixOperators: true
  ExcludeOperators: false
  ExcludeSetters: false
  MaxLength: 50
  Excluded:
  - spec/*
  Enabled: true
  Severity: Convention
