FROM crystallang/crystal:0.36.0-alpine

WORKDIR /app

# Set the commit through a build arg
ARG PLACE_COMMIT="DEV"

# Add trusted CAs for communicating with external services
RUN apk add --no-cache ca-certificates tzdata bash

RUN update-ca-certificates

RUN apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing watchexec

COPY shard.yml /app
COPY shard.override.yml /app
COPY shard.lock /app

RUN shards install

COPY entrypoint.sh /app/entrypoint.sh

# These provide certificate chain validation where communicating with external services over TLS
ENV SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt

CMD /app/entrypoint.sh
