#! /usr/bin/env bash

set -eu

# this function is called when Ctrl-C is sent
function trap_ctrlc ()
{
    echo "### cleaning up"
    docker-compose down
    exit 2
}

# initialise trap to call trap_ctrlc function
# when signal 2 (SIGINT) is received
trap "trap_ctrlc" 2

docker-compose pull

docker-compose build

docker-compose run --rm api /app/entrypoint.sh "$@"

docker-compose down
