require "../helper"

module PlaceOS::Api
  # The Ldap/Saml/OAuth authentication controllers are generated by a single
  # macro (controllers/authentications.cr) — exercise all three the same way.
  # NOTE: the Saml generator is `adfs_strat` (returns a SamlAuthentication).
  {% for entry in [{"Ldap", "ldap_strat"}, {"Saml", "adfs_strat"}, {"OAuth", "oauth_strat"}] %}
    describe {{entry[0].id}}Authentications do
      base = {{entry[0].id}}Authentications.base_route

      describe "index", tags: "search" do
        it "lists authentication strategies" do
          strat = Model::Generator.{{entry[1].id}}.save!
          strat.persisted?.should be_true

          result = client.get(base, headers: Spec::Authentication.headers)
          result.status_code.should eq 200

          ids = Array(Hash(String, JSON::Any)).from_json(result.body).map(&.["id"].as_s)
          ids.should contain(strat.id)
          result.headers["X-Total-Count"].to_i64.should be >= 1
        end

        it "filters by authority_id" do
          authority_a = Model::Generator.authority("a-#{random_name}.example.com").save!
          authority_b = Model::Generator.authority("b-#{random_name}.example.com").save!

          strat_a = Model::Generator.{{entry[1].id}}(authority_a).save!
          strat_b = Model::Generator.{{entry[1].id}}(authority_b).save!

          params = HTTP::Params.encode({"authority_id" => authority_a.id.as(String)})
          result = client.get("#{base}?#{params}", headers: Spec::Authentication.headers)
          result.status_code.should eq 200

          results = Array(Hash(String, JSON::Any)).from_json(result.body)
          results.should_not be_empty
          ids = results.map(&.["id"].as_s)
          ids.should contain(strat_a.id)
          ids.should_not contain(strat_b.id)
          results.all? { |r| r["authority_id"].as_s == authority_a.id }.should be_true
        end

        it "filters by name via q" do
          strat = Model::Generator.{{entry[1].id}}
          strat.name = random_name
          strat.save!

          params = HTTP::Params.encode({"q" => strat.name})
          result = client.get("#{base}?#{params}", headers: Spec::Authentication.headers)
          result.status_code.should eq 200

          results = Array(Hash(String, JSON::Any)).from_json(result.body)
          results.size.should eq 1
          results.first["id"].as_s.should eq strat.id
          result.headers["X-Total-Count"].should eq "1"
        end
      end

      describe "access control", tags: "access-control" do
        it "is admin-only" do
          _, headers = Spec::Authentication.authentication(sys_admin: false, support: false)
          result = client.get(base, headers: headers)
          result.status_code.should eq 403
        end
      end
    end
  {% end %}
end
